<?php 

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) exit;

return apply_filters(
    'srwc_default_options',
    array(
        'srwc_settings'     => array(       
            'enable'                        => 'yes',
            'spin_per_email'                => 1,
            'time_spin_between'             => 24,
            'popup_trigger'                 => 'show_wheel',
            'initial_delay'                 => 0,
            'time_on_close'                 => 1,
            'show_again'                    => 24,
            'hide_icon'                     => 'yes',
            'shop_page'                     => 'yes',
            'home_page'                     => 'no',
            'blog_page'                     => 'no',
            'conditional_tags'              => '',
            'icon_display_position'         => 'bottom-right',
            'custom_popup_icon_image'       => '',
            'custom_icon_color'             => '#ffffff',
            'custom_icon_bg_color'          => '#dd3333',
            'user_name'                     => 'no',
            'user_name_require'             => 'no',
            'name_border'                   => 10,
            'email_border'                  => 10,
            'auto_hide_wheel'               => 0,
            'win_message'                   => 'Congratulations! You have won a {coupon_label} discount coupon. The coupon has been sent to the email address you provided when spinning. Redeem it at checkout {checkout} now!',
            'lose_message'                  => 'OOPS! No luck this time. Try again!',
            'gdpr_checkbox'                 => 'no',
            'gdpr_message'                  => 'I agree with the term and condition',
            'code_type'                     => 'alphanumeric',
            'coupon_length'                 => 6,
            'coupon_prefix'                 => '',
            'coupon_suffix'                 => '',
            'coupon_expiry_days'            => 30,
            'allow_free_shipping'           => 'no',
            'email_restrictions'            => 'no',
            'individual_use_only'           => 'no',
            'exclude_sale'                  => 'no',
            'minimum_spend'                 => '',
            'maximum_spend'                 => '',
            'limit_coupon'                  => 1,
            'limit_coupon_to_x_items'       => 1,
            'limit_coupon_per_user'         => 1,
            'wheel_speed_spin'              => '3',
            'wheel_pointer'                 => 'center',
            'wheel_pointer_color'           => '#f70707',
            'wheel_pointer_type'            => 'color',
            'wheel_center_color'            => '#ffffff',
            'wheel_border_color'            => '#ffffff',
            'background_blend_mode'         => 'none',
            'background_color'              => '#1e73be',
            'text_color'                    => '#ffffff',
            'rewards_title'                 => 'SPIN TO WIN!',
            'spin_button_text'              => 'Spin Now',
            'spin_button_text_size'         => 18,
            'spin_button_border'            => 10,
            'spin_button_text_color'        => '#ffffff',
            'spin_button_bg_color'          => '#ff9000',
            'spin_button_hover_bg_color'    => '#ffad42',
            'wheel_text_size'               => 18,
            'wheel_size'                    => 100,
            'display_currency'              => 'symbol',
            'enable_customer_email'         => 'yes',
            'enable_mailchimp'              => 'no',
            'name_required_message'         => 'Please enter your name',
            'email_required_message'        => 'Please enter your email',
            'email_invalid_message'         => 'Please enter a valid email address',
            'spin_limit_email_message'      => 'You’ve reached your spin limit.',
            'wait_spin_message'             => 'You must wait {time} before spinning again.',
            'gdpr_required_message'         => 'Please agree with our term and condition.',
            'error_message_color'           => '#ffffff',
            'error_message_font_size'       => 14,
            'slides' => array(
                'coupon_type' => array(
                    '0' => 'none',
                    '1' => 'none',
                    '2' => 'percent',
                    '3' => 'none',
                    '4' => 'percent',
                    '5' => 'none',
                    '6' => 'fixed_product',
                ),
                'label' => array(
                    '0' => 'Not Lucky',
                    '1' => 'Not Lucky',
                    '2' => '{coupon_amount} OFF',
                    '3' => 'Not Lucky',
                    '4' => '{coupon_amount} OFF',
                    '5' => 'Not Lucky',
                    '6' => '{coupon_amount} OFF',
                ),
                'value' => array(
                    '0' => '0',
                    '1' => '0',
                    '2' => '5',
                    '3' => '0',
                    '4' => '10',
                    '5' => '0',
                    '6' => '5',
                ),
                'coupon_code' => array(
                    '0' => '',
                    '1' => '',
                    '2' => '',
                    '3' => '',
                    '4' => '',
                    '5' => '',
                    '6' => '',
                ),
                'probability' => array(
                    '0' => '17',
                    '1' => '17',
                    '2' => '17',
                    '3' => '17',
                    '4' => '17',
                    '5' => '17',
                    '6' => '15',
                ),
                'color' => array(
                    '0' => '#ffa011',
                    '1' => '#ffa011',
                    '2' => '#2546ea',
                    '3' => '#01b2ac',
                    '4' => '#8224e3',
                    '5' => '#dd3333',
                    '6' => '#204707',
                ),
            ),
        ),
    )
);